<?php

declare(strict_types=1);

namespace Net\NNTP\Tests\Unit;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Ensures that the response code constants defined in Responsecode.php are
 * loaded and have the correct integer values.
 */
final class ResponsecodeTest extends TestCase
{
    #[DataProvider('constantsProvider')]
    public function testConstantIsDefined(string $name, int $expected): void
    {
        $this->assertTrue(defined($name), "Constant $name should be defined");
        $this->assertSame($expected, constant($name));
    }

    /**
     * @return array<string, array{string, int}>
     */
    public static function constantsProvider(): array
    {
        return [
            // Session
            'READY_POSTING_ALLOWED'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_READY_POSTING_ALLOWED', 200],
            'READY_POSTING_PROHIBITED' => ['NET_NNTP_PROTOCOL_RESPONSECODE_READY_POSTING_PROHIBITED', 201],
            'SLAVE_RECOGNIZED'         => ['NET_NNTP_PROTOCOL_RESPONSECODE_SLAVE_RECOGNIZED', 202],

            // Errors
            'UNKNOWN_COMMAND' => ['NET_NNTP_PROTOCOL_RESPONSECODE_UNKNOWN_COMMAND', 500],
            'SYNTAX_ERROR'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_SYNTAX_ERROR', 501],
            'NOT_PERMITTED'   => ['NET_NNTP_PROTOCOL_RESPONSECODE_NOT_PERMITTED', 502],
            'NOT_SUPPORTED'   => ['NET_NNTP_PROTOCOL_RESPONSECODE_NOT_SUPPORTED', 503],

            // Group selection
            'GROUP_SELECTED'   => ['NET_NNTP_PROTOCOL_RESPONSECODE_GROUP_SELECTED', 211],
            'NO_SUCH_GROUP'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_NO_SUCH_GROUP', 411],
            'NO_GROUP_SELECTED'=> ['NET_NNTP_PROTOCOL_RESPONSECODE_NO_GROUP_SELECTED', 412],

            // Article retrieval
            'ARTICLE_FOLLOWS'         => ['NET_NNTP_PROTOCOL_RESPONSECODE_ARTICLE_FOLLOWS', 220],
            'HEAD_FOLLOWS'            => ['NET_NNTP_PROTOCOL_RESPONSECODE_HEAD_FOLLOWS', 221],
            'BODY_FOLLOWS'            => ['NET_NNTP_PROTOCOL_RESPONSECODE_BODY_FOLLOWS', 222],
            'ARTICLE_SELECTED'        => ['NET_NNTP_PROTOCOL_RESPONSECODE_ARTICLE_SELECTED', 223],
            'NO_ARTICLE_SELECTED'     => ['NET_NNTP_PROTOCOL_RESPONSECODE_NO_ARTICLE_SELECTED', 420],
            'NO_NEXT_ARTICLE'         => ['NET_NNTP_PROTOCOL_RESPONSECODE_NO_NEXT_ARTICLE', 421],
            'NO_PREVIOUS_ARTICLE'     => ['NET_NNTP_PROTOCOL_RESPONSECODE_NO_PREVIOUS_ARTICLE', 422],
            'NO_SUCH_ARTICLE_NUMBER'  => ['NET_NNTP_PROTOCOL_RESPONSECODE_NO_SUCH_ARTICLE_NUMBER', 423],
            'NO_SUCH_ARTICLE_ID'      => ['NET_NNTP_PROTOCOL_RESPONSECODE_NO_SUCH_ARTICLE_ID', 430],

            // Transfer
            'TRANSFER_SEND'     => ['NET_NNTP_PROTOCOL_RESPONSECODE_TRANSFER_SEND', 335],
            'TRANSFER_SUCCESS'  => ['NET_NNTP_PROTOCOL_RESPONSECODE_TRANSFER_SUCCESS', 235],
            'TRANSFER_UNWANTED' => ['NET_NNTP_PROTOCOL_RESPONSECODE_TRANSFER_UNWANTED', 435],
            'TRANSFER_FAILURE'  => ['NET_NNTP_PROTOCOL_RESPONSECODE_TRANSFER_FAILURE', 436],
            'TRANSFER_REJECTED' => ['NET_NNTP_PROTOCOL_RESPONSECODE_TRANSFER_REJECTED', 437],

            // Posting
            'POSTING_SEND'       => ['NET_NNTP_PROTOCOL_RESPONSECODE_POSTING_SEND', 340],
            'POSTING_SUCCESS'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_POSTING_SUCCESS', 240],
            'POSTING_PROHIBITED' => ['NET_NNTP_PROTOCOL_RESPONSECODE_POSTING_PROHIBITED', 440],
            'POSTING_FAILURE'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_POSTING_FAILURE', 441],

            // Auth
            'AUTHORIZATION_REQUIRED'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_AUTHORIZATION_REQUIRED', 450],
            'AUTHORIZATION_CONTINUE'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_AUTHORIZATION_CONTINUE', 350],
            'AUTHORIZATION_ACCEPTED'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_AUTHORIZATION_ACCEPTED', 250],
            'AUTHORIZATION_REJECTED'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_AUTHORIZATION_REJECTED', 452],
            'AUTHENTICATION_REQUIRED'   => ['NET_NNTP_PROTOCOL_RESPONSECODE_AUTHENTICATION_REQUIRED', 480],
            'AUTHENTICATION_CONTINUE'   => ['NET_NNTP_PROTOCOL_RESPONSECODE_AUTHENTICATION_CONTINUE', 381],
            'AUTHENTICATION_ACCEPTED'   => ['NET_NNTP_PROTOCOL_RESPONSECODE_AUTHENTICATION_ACCEPTED', 281],
            'AUTHENTICATION_REJECTED'   => ['NET_NNTP_PROTOCOL_RESPONSECODE_AUTHENTICATION_REJECTED', 482],

            // Informational
            'HELP_FOLLOWS'         => ['NET_NNTP_PROTOCOL_RESPONSECODE_HELP_FOLLOWS', 100],
            'CAPABILITIES_FOLLOW'  => ['NET_NNTP_PROTOCOL_RESPONSECODE_CAPABILITIES_FOLLOW', 101],
            'SERVER_DATE'          => ['NET_NNTP_PROTOCOL_RESPONSECODE_SERVER_DATE', 111],
            'GROUPS_FOLLOW'        => ['NET_NNTP_PROTOCOL_RESPONSECODE_GROUPS_FOLLOW', 215],
            'OVERVIEW_FOLLOWS'     => ['NET_NNTP_PROTOCOL_RESPONSECODE_OVERVIEW_FOLLOWS', 224],
            'HEADERS_FOLLOW'       => ['NET_NNTP_PROTOCOL_RESPONSECODE_HEADERS_FOLLOW', 225],
            'NEW_ARTICLES_FOLLOW'  => ['NET_NNTP_PROTOCOL_RESPONSECODE_NEW_ARTICLES_FOLLOW', 230],
            'NEW_GROUPS_FOLLOW'    => ['NET_NNTP_PROTOCOL_RESPONSECODE_NEW_GROUPS_FOLLOW', 231],

            // Misc
            'WRONG_MODE'            => ['NET_NNTP_PROTOCOL_RESPONSECODE_WRONG_MODE', 401],
            'INTERNAL_FAULT'        => ['NET_NNTP_PROTOCOL_RESPONSECODE_INTERNAL_FAULT', 403],
            'BASE64_ENCODING_ERROR' => ['NET_NNTP_PROTOCOL_RESPONSECODE_BASE64_ENCODING_ERROR', 504],
        ];
    }
}

